### ISSUE TITLE
Add Title field to user model

### ISSUE THREAD

**Issue by JoshBurke** [hack4impact-uiuc/life-after-hate#149]
**Is your feature request related to a problem? Please describe.**
The admin panel mockup has a column for title, but this doesn't exist in the user database model. Right now we're just rendering the account type/ role in this column, despite the fact that we already have a column for account type.

**Describe the solution you'd like**
I think it would be a good idea to have this as a default empty field, but make it editable in the admin panel. This would allow for more descriptive roles and distinction between director vs. another type of admin, even if it's just informative and serves no functional purpose.

**Additional context**
Probably just needs to be a small backend/database fix, one or two lines.

**Comment by JoshBurke** [comment]
Any opinions?

**Comment by josh-byster** [comment]
Good catch! You're right that we don't have support for that, and this is something we should absolutely add based on the design. @eckels brought up that it might be nice to have a way for admins to edit those fields directly. Looping in @alan-fang for discussion as well.

@Polarpi would you mind taking this on?
