### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined when loading resources 

### ISSUE THREAD

**Issue by alan-fang** [hack4impact-uiuc/life-after-hate#160]
**Describe the bug**
Frontend breaks when trying to add a resource

**To Reproduce**

Run LAHUtil with no data in backend, and try to add a resource

**Expected behavior**
Shouldn't break, but breaks :( 

**Screenshots**
<img width="828" alt="Screen Shot 2020-02-24 at 4 05 01 PM" src="https://user-images.githubusercontent.com/21253247/75195439-8d08fa80-571f-11ea-91c6-ee8eb310791a.png">

**Additional context**
Normally would assign to @angadgarg25 , but maybe someone else can pick it up while he's in India 🇮🇳

**Comment by josh-byster** [comment]
Possibly hotfixed on master

**Comment by alan-fang** [comment]
Checked on master, the issue doesn't seem to persist any more which is nice. Bad thing: we found another bug #175 , so we'll have to check that out :( . Thanks for the fix @josh-byster!
