### ISSUE TITLE
Restrict Map Bounds to [Continental] US

### ISSUE THREAD

**Issue by alan-fang** [hack4impact-uiuc/life-after-hate#166]
**Is your feature request related to a problem? Please describe.**
This is tentative, but I'm _pretty_ sure that the resource partners are all in the continental US. It would greatly improve user quality if we were able to restrict the map view to the continental US only. 

**Describe the solution you'd like**
We can adjust map bounds on the map to restrict the view to the continental US

**Additional context**
https://docs.mapbox.com/mapbox-gl-js/example/restrict-bounds/

**Comment by alan-fang** [comment]
blocked on Angela's response to email sent on 2/26

**Comment by josh-byster** [comment]
Haha, great minds think alike—I *just* [changed it](https://github.com/hack4impact-uiuc/life-after-hate/pull/163/files#diff-aa19270a9dbbb32c06c384bc875c1a62) the night before you wrote this.

**Comment by josh-byster** [comment]
Fixed in #163
