### ISSUE TITLE
Tag filtering

### ISSUE THREAD

**Issue by alan-fang** [hack4impact-uiuc/life-after-hate#196]
**Is your feature request related to a problem? Please describe.**
One of the great things about our app is that it assigns tags onto resources, but we don't do much with the tags themselves — they're only used on the backend with a search weight. 

**Describe the solution you'd like**
Let's implement v1 of tag filtering. When you click on a tag in the map side panel, you should filter the existing pins on the map to only the pins in that filter. For now we'll only support filtering by a single tag, but maybe in the future we can support multiple tags.

<img width="342" alt="Screen Shot 2020-03-11 at 2 19 43 AM" src="https://user-images.githubusercontent.com/21253247/76392056-d459d280-633e-11ea-8626-4c2f5590c18a.png">

For example, clicking on the `Cabins` tag should only display resources with that tag in the existing search criteria.

**Additional context**
Add details, any other context or screenshots about the feature request here.
We should also consider the ability to "undo" a tag filter after it is applied.

**Comment by alan-fang** [comment]
3/11/20 update: for v1 let's ship out the client side API ability to filter pins based on a tag. After we get designs from @eckels we can continue building out the rest of the experience flow

**Comment by eckels** [comment]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/17066287/77958061-1ae58180-729a-11ea-8ded-fb5a24fcf67a.png">
Here is a basic view of what a tag should look like on this search area after you click on it. It would expand the size of the search box, but only when the tag is there. I'm not sure how it is coded, but it would be nice for the height of the box to change depending on if the tag is there vs absent.
