### ISSUE TITLE
Giving Admins option to edit or view a particular resource

### ISSUE THREAD

**Issue by eckels** [hack4impact-uiuc/life-after-hate#210]
**Is your feature request related to a problem? Please describe.**
Currently if you are an admin and you go to the modal window you are brought to the edit resource screen. If you are a volunteer, the modal window only allows you to view. So essentially we have two modal windows, edit and view, that are currently exclusively accessed by either the Admin or volunteer respectively. 

**Describe the solution you'd like**
We still want the volunteer to only have access to view resource, so that will stay the same. But for the admin we want them to have the option to **view or edit** the resource. To do this, we need to modify the three fields that allow us to access the window. These are currently located here for the map view:
![image](https://user-images.githubusercontent.com/17066287/79019160-56563a80-7b3b-11ea-996e-37a19c2433f8.png)

We also need to modify it on the directory view page.
![image](https://user-images.githubusercontent.com/17066287/79019241-8d2c5080-7b3b-11ea-89db-a7021d387fb2.png)

Currently we have logic to display different buttons depending on if the user is an Admin or volunteer. We can use this logic to help us build an interface that includes two buttons for the admin, allowing them to choose between editing or viewing. This styling can be applied to the expanded card and the map pin.
![image](https://user-images.githubusercontent.com/17066287/79023152-33c91f00-7b45-11ea-8ebd-884d1ca4a94e.png)

For the icon in the top right of the condensed card, we will be replacing that with an svg icon that looks like this:
![image](https://user-images.githubusercontent.com/17066287/79023246-607d3680-7b45-11ea-9d95-1058880a1b47.png)

For the directory view, we will just add another button right by the edit. I'm currently working on maybe making it a little easier to distinguish, but this probably very close to what the final design would be. 
![image](https://user-images.githubusercontent.com/17066287/79023446-f913b680-7b45-11ea-942e-5bc737d85179.png)

**Comment by alan-fang** [comment]
This looks good!

**Comment by josh-byster** [comment]
Nice work on this, @eckels! :)
