### ISSUE TITLE
Basic Sorting in Directory View

### ISSUE THREAD

**Issue by alan-fang** [hack4impact-uiuc/life-after-hate#377]
**Describe the solution you'd like**

When clicking on the category headers (i.e. Resource Name, Location), add functionality to alphabetically sort cards based on which header is clicked.

<img width="1416" alt="Screen Shot 2020-05-28 at 3 25 57 PM" src="https://user-images.githubusercontent.com/21253247/83190128-8eb7d500-a0f7-11ea-9c17-2dec40b7f665.png">

**Additional context**
Add details, any other context or screenshots about the feature request here.
@josh-byster can you advise on the technical complexity behind this? I think it's limited to frontend work.

**Comment by josh-byster** [comment]
Looks good! Should be a quick change that's limited in scope to frontend work—I imagine the best way to approach is by adding a redux action to apply a sort of resources, and we can store the field in which we're sorting along with the order `asc/desc`. Then the reducer will respond to this change by returning a sort on the resources.
