### ISSUE TITLE
Add general server error handler

### ISSUE THREAD

**Issue by josh-byster** [hack4impact-uiuc/life-after-hate#42]
**Is your feature request related to a problem? Please describe.**

When there's an unhandled promise rejection in our code, we don't want the server to return no response, but rather a 500 with more details (potentially on what went wrong).

**Describe the solution you'd like**

Add some form of [errorWrap and handler](https://github.com/hack4impact-uiuc/h4i-recruitment/tree/master/backend/src/middleware) like in the recruitment portal. 

We essentially want to have it such that if our async methods throw an exception unexpectedly (i.e. we don't intend this to happen), then actually return an error message in response.
Said another way, we _don't_ want this error wrapper to ever be called. It should be a worst-case scenario that says "Oh, something happened." But rather than just not returning a response and letting the user hang (like it does now if there's an exception in an async route), it will return an error object. We can use `Boom`'s error object to send back a server error.

**Additional context**
Add details, any other context or screenshots about the feature request here.

[This ](https://madole.xyz/error-handling-in-express-with-async-await-routes) is a good walkthrough of how it should look at a high level.

**Comment by alan-fang** [comment]
@laurenho025 @abetco 

Specifically Albert who's writing some of the API wrappers on the frontend, you may find it useful to sync with Rebecca on how these are handled so that we achieve parity on both client and server-side error handling
