### ISSUE TITLE
Edit History

### ISSUE THREAD

**Issue by alan-fang** [hack4impact-uiuc/life-after-hate#48]
**Is your feature request related to a problem? Please describe.**
Over the past weeks, we've mentioned the concept of a "ground truth" for our final data source. That data will sit in Salesforce, and it is possible that our app will be able to talk directly to the data stored there.

In order to do so, we need to add guardrails such that incorrect changes to data in Salesforce are recoverable, and do not permanently corrupt the ground truth data.

**Describe the solution you'd like**
In these coming weeks, we'll look to implement a way for an administrator to view the edit history of a given resource, and to revert the current resource to that snapshot. There are a couple of ways you can do this, and there are different benefits to each approach! Some questions to think about:

- When a change is made, will you snapshot the entire resource, or just mark the specific change to replay?

- How will your abstraction handle load? Will it be able to scale gracefully to 1000s of resources? 10000s? Think of this in terms of both speed and space usage.

- Should we set up an intermediate data source to handle inconsistency? Or should we allocate work to the backend server we currently have setup?

**Additional context**
Since this is a bigger feature on backend, we're going to have you both spec the granularities (DB design, API calls, and yes, documentation) of what you will need to implement, as well as discuss design choices, testing, and time estimates of each sub-task within this feature request. You can see the tech spec template [here](https://docs.google.com/document/d/158fexdDJWKrnRHX8BPpHxxGEooizLxaKUpNrFISu4RI/edit) as well as sample tech specs [here](https://docs.google.com/document/d/1N8gOLEouQabimAJknXJ3l_GCFv85oSjNLaaY_uonF80/edit).

**Comment by josh-byster** [comment]
Some helpful links:

https://stackoverflow.com/questions/3507624/mongodb-nosql-keeping-document-change-history
https://stackoverflow.com/questions/4185105/ways-to-implement-data-versioning-in-mongodb

**Comment by gwang0136** [comment]
https://docs.google.com/document/d/18MB4GXruD-6wY7oLIDoPLlFn1ti9E1wxYNmyR7BJ-7E/edit#
