### ISSUE TITLE
Add "Email" Field / Permissions

### ISSUE THREAD

**Issue by josh-byster** [hack4impact-uiuc/life-after-hate#53]
**Is your feature request related to a problem? Please describe.**

We would also like to get user email when they sign up and store that in our DB.

**Describe the solution you'd like**

We can accomplish this by updating the model to include `email` and using the "email" scope with Google OAuth.

**Additional context**
Add details, any other context or screenshots about the feature request here.

**Comment by alan-fang** [comment]
I think @gwang0136 can tackle this while we catch Rebecca up with what needs to be done re: edit history
