### ISSUE TITLE
Keyword Extraction

### ISSUE THREAD

**Issue by alan-fang** [hack4impact-uiuc/life-after-hate#75]
**Is your feature request related to a problem? Please describe.**
In LAH's volunteer input form, data is mostly unstructured and submitted in the form of notes. For example:

> I'm currently completing a master's degree and am applying to PhD programs. I have studied [topic] extensively for my thesis in my undergraduate and in my masters degrees. I have also been volunteered in my community for various social justice initiatives.

As it stands, we'd like for a better way to store the most relevant metadata in it's own data fields such that we can better query and categorize the existing data in the volunteer form.

**Describe the solution you'd like**
Again, let's use this example (fake) snippet for context:
> I'm currently completing a master's degree and am applying to PhD programs. I have studied [topic] extensively for my thesis in my undergraduate and in my masters degrees. I have also been volunteered in my community for various social justice initiatives.

We'd like to be able to extract most (if not all) of the keywords and dump them into the tags field in `Resources`. In this case, we'd probably want `masters`, `PhD`, `[topic]`, `thesis`, `undergraduate`, `social justice`, `volunteer`.

Writing a migration script would help us better format the data in the volunteer form and dump it into our mongo instance.

**Additional context**
For data context, please take a look at `Mock Volunteer Form_Confidential.xlsx` in the Google Drive

**Comment by gwang0136** [comment]
https://www.npmjs.com/package/keyword-extractor
