### ISSUE TITLE
Buildout FE for Admin User Management Page

### ISSUE THREAD

**Issue by josh-byster** [hack4impact-uiuc/life-after-hate#92]
**Is your feature request related to a problem? Please describe.**

As an admin, I should be able to:

- See all the users in the platform
- Approve users
- Delete users
- Change role of existing users (upgrade or downgrade privilege)

**Describe the solution you'd like**

Since all the work has been done on the backend, what's left is purely buildout of the UI for each  of the above components.

**Comment by alan-fang** [comment]
blocked: need designs from @eckels
